name: Publish Container Images

on:
  schedule:
    - cron: '35 7 * * *'
  push:
    branches: 
      - main
      - master
    tags: [ '*.*.*' ]
  pull_request:
    branches:
      - main
      - master

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app image
        id: build-and-push-app
        uses: docker/build-push-action@v2
        with:
          context: .
          target: app
          push: ${{ github.event_name != 'pull_request' }}
          tags: eher/miniature-spoon/app:latest

      - name: Build and push app-dev image
        id: build-and-push-app-dev
        uses: docker/build-push-action@v2
        with:
          context: .
          target: app-dev
          push: ${{ github.event_name != 'pull_request' }}
          tags: eher/miniature-spoon/app-dev:latest

      - name: Build and push web image
        id: build-and-push-web
        uses: docker/build-push-action@v2
        with:
          context: .
          target: web
          push: ${{ github.event_name != 'pull_request' }}
          tags: eher/miniature-spoon/web:latest

      - name: Build and push web-dev image
        id: build-and-push-web-dev
        uses: docker/build-push-action@v2
        with:
          context: .
          target: web-dev
          push: ${{ github.event_name != 'pull_request' }}
          tags: eher/miniature-spoon/web-dev:latest
